/**
 * Source of truth for the Client/Project configuration hierarchy — mirrors the pattern in
 * permissions.js (a plain list here, reconciled into the ConfigDef table by prisma/seed.js).
 * Each entry becomes an admin-editable setting: a client can override the default, and a
 * project can override the client's value, without any code change. New phases add settings
 * here (SLA thresholds, escalation rules, branding, ...) instead of hardcoding them per client.
 */
const CONFIG_DEFS = [
  {
    key: 'pdf.footerText',
    label: 'PDF report footer text',
    description: 'Printed at the bottom of every generated stage report PDF.',
    valueType: 'STRING',
    scope: 'BOTH',
    defaultValue: 'Generated by NaKJM Infra Field App · Confidential — for internal project execution records only.',
  },
  {
    key: 'photo.minGpsAccuracyMeters',
    label: 'Minimum required GPS accuracy (meters)',
    description:
      'Photos captured with a reported GPS accuracy worse (larger) than this are rejected at upload time. Set to 0 to disable the check.',
    valueType: 'NUMBER',
    scope: 'BOTH',
    defaultValue: 0,
  },
];

module.exports = { CONFIG_DEFS };
