/**
 * Livanto Green hardware catalog — sourced from livantogreen.com/products.
 * Every field here is real. Do not add specs, certifications or prices
 * that aren't confirmed on the source site.
 */
export const PRODUCTS = [
  {
    id: 'ac-7-4',
    category: 'AC',
    name: '7.4 kW AC Charger',
    power: 7.4,
    powerLabel: '7.4 kW',
    connector: 'Type-2',
    tagline: 'Everyday charging, done right.',
    description: 'High-performance Type-2 AC charger with smart charging capabilities.',
    features: ['Type-2 connector', 'Smart charging'],
    applications: ['Residential', 'Workplace', 'Light commercial'],
  },
  {
    id: 'ac-ad-wall-22',
    category: 'AC',
    name: 'AD Wall Smart Charger',
    power: 22,
    powerLabel: '22 kW',
    connector: 'Type-2',
    tagline: 'A charger that pays for its own wall space.',
    description: 'Smart display-enabled charger with a 15.6" HD screen and an advertising platform.',
    features: ['15.6" HD display', 'Advertising platform', 'Smart charging'],
    applications: ['Premium retail', 'High-footfall parking'],
  },
  {
    id: 'dc-30',
    category: 'DC',
    name: '30 kW DC Charger',
    power: 30,
    powerLabel: '30 kW',
    connector: 'CCS2',
    tagline: 'Fast charging for everyday commercial use.',
    description: 'High-power DC fast charging station with a CCS2 connector.',
    features: ['CCS2 connector', 'DC fast charging'],
    applications: ['Commercial fleets', 'Public charging hubs'],
  },
  {
    id: 'dc-60',
    category: 'DC',
    name: '60 kW DC Charger',
    power: 60,
    powerLabel: '60 kW',
    connector: 'Dual CCS2',
    tagline: 'Certified for the highway.',
    description: 'ARAI-certified 60 kW DC fast charger with dual CCS2 connectors and dynamic load balancing.',
    features: ['ARAI Certified', 'Dual CCS2', 'Dynamic load balancing'],
    applications: ['Highway pit stops', 'Fast-turnaround locations'],
    featured: true,
  },
  {
    id: 'dc-120',
    category: 'DC',
    name: '120 kW DC Charger',
    power: 120,
    powerLabel: '120 kW',
    connector: 'CCS2',
    tagline: 'Built for throughput.',
    description: 'High-power DC fast charger sized for commercial charging plazas.',
    features: ['CCS2 connector', 'High-throughput duty cycle'],
    applications: ['High-throughput commercial plazas'],
  },
  {
    id: 'dc-180',
    category: 'DC',
    name: '180 kW DC Charger',
    power: 180,
    powerLabel: '180 kW',
    connector: 'CCS2',
    tagline: 'For fleets that don’t stop.',
    description: 'High-power DC fast charger for heavy-duty, high-frequency fleet operations.',
    features: ['CCS2 connector', 'Heavy-duty rated'],
    applications: ['Logistics hubs', 'Heavy-duty EV fleets'],
  },
  {
    id: 'dc-240',
    category: 'DC',
    name: '240 kW DC Charger',
    power: 240,
    powerLabel: '240 kW',
    connector: 'Dual CCS2',
    tagline: 'Industry leading speed.',
    description: 'Dual-CCS2 ultra-fast DC charger engineered for rapid turnaround.',
    features: ['Dual CCS2', 'Industry leading speed'],
    applications: ['Ultra-fast charging corridors', 'OEM partner sites'],
    featured: true,
  },
  {
    id: 'dc-360',
    category: 'DC',
    name: '360 kW DC Charger',
    power: 360,
    powerLabel: '360 kW',
    connector: 'CCS2',
    tagline: 'The flagship.',
    description: 'Livanto’s highest-power DC charger, for installations that need the fastest possible turnaround.',
    features: ['CCS2 connector', 'Flagship duty rating'],
    applications: ['Flagship installations'],
  },
];

export const POWER_OPTIONS = PRODUCTS.map((p) => ({
  value: p.id,
  label: p.powerLabel,
}));
