/**
 * Livanto Green hardware catalog — sourced from the official Livanto
 * Green company profile ("Hardware Portfolio" slide) plus
 * livantogreen.com/products. Every field here is real. Do not add specs,
 * certifications or prices that aren't confirmed on those sources.
 */
export const PRODUCTS = [
  {
    id: 'livanto-home',
    category: 'AC',
    name: 'Livanto Home',
    power: 7.4,
    powerLabel: '7.4 kW',
    connector: 'Type-2',
    tagline: 'Everyday charging, done right.',
    description: 'Compact AC charger designed in-house for residential charging — built to withstand India’s heat, humidity and dust.',
    features: ['Type-2 connector', 'OCPP smart charging', 'OTA firmware upgrades'],
    applications: ['Residential'],
    image: '/products/livanto-home.png',
  },
  {
    id: 'livanto-wall',
    category: 'AC',
    name: 'Livanto Wall',
    power: 22,
    powerLabel: '7.4 / 22 kW',
    connector: 'Type-2 · Socket',
    tagline: 'Wall-mounted, workplace ready.',
    description: 'Wall or pedestal-mounted AC charger for workplaces, RWAs and light commercial sites.',
    features: ['Type-2 connector', 'OCPP smart charging', 'OTA firmware upgrades'],
    applications: ['Workplace', 'RWA / residential'],
    image: '/products/livanto-wall.png',
  },
  {
    id: 'livanto-ac-dual',
    category: 'AC',
    name: 'Livanto AC Dual',
    power: 22,
    powerLabel: '22 kW',
    connector: 'Dual Gun',
    tagline: 'Two vehicles, one pedestal.',
    description: 'Dual-gun AC charging for higher-throughput commercial and public parking sites.',
    features: ['Dual gun', 'OCPP smart charging', 'State-of-the-art hardware + software'],
    applications: ['Commercial', 'Public parking'],
    image: '/products/livanto-ac-dual.png',
  },
  {
    id: 'livanto-dc-60',
    category: 'DC',
    name: 'Livanto DC 60',
    power: 60,
    powerLabel: '60 kW',
    connector: 'Dual Gun · CCS2',
    tagline: 'Fast charging, franchise-ready.',
    description: 'The entry point to the Livanto DC franchise line — dual-gun DC fast charging for cars.',
    features: ['Dual CCS2 gun', 'OCPP 1.6J', '7" HMI LED display', '-20°C to 70°C rated'],
    applications: ['Public charging hubs', 'Franchise stations'],
    image: '/products/livanto-dc-60.png',
    franchiseKw: 60,
  },
  {
    id: 'livanto-dc-120',
    category: 'DC',
    name: 'Livanto DC 120',
    power: 120,
    powerLabel: '120 kW',
    connector: 'Dual Gun · CCS2',
    tagline: 'Built for throughput.',
    description: 'Higher-power DC fast charging for commercial plazas and higher-traffic franchise sites.',
    features: ['Dual CCS2 gun', 'OCPP 1.6J', '7" HMI LED display', '-20°C to 70°C rated'],
    applications: ['Commercial plazas', 'Franchise stations'],
    image: '/products/livanto-dc-120.png',
    franchiseKw: 120,
    featured: true,
  },
  {
    id: 'livanto-dc-240',
    category: 'DC',
    name: 'Livanto DC 240',
    power: 240,
    powerLabel: '240 kW',
    connector: 'Dual Gun · CCS2',
    tagline: 'Fleet-grade, bus & truck ready.',
    description: 'Livanto’s highest-power charger, engineered for bus and truck fleets on the franchise line.',
    features: ['Dual CCS2 gun', 'OCPP 1.6J', '7" HMI LED display', '-20°C to 70°C rated'],
    applications: ['Bus / truck fleets', 'Highway corridors'],
    image: '/products/livanto-dc-240.png',
    franchiseKw: 240,
    featured: true,
  },
];

export const POWER_OPTIONS = PRODUCTS.map((p) => ({
  value: p.id,
  label: p.powerLabel,
}));
