const ROLES = {
  ADMIN: 'ADMIN',
  OPERATIONS: 'OPERATIONS',
  FINANCE: 'FINANCE',
  FRANCHISE: 'FRANCHISE',
};

const STATION_TYPES = ['PUBLIC', 'FLEET', 'FRANCHISE', 'BSS_HUB'];
const ASSET_TYPES   = ['CHARGER', 'BSS', 'TRANSFORMER', 'SOLAR'];
const CHARGER_STATUSES = ['AVAILABLE', 'CHARGING', 'FAULT', 'OFFLINE', 'RESERVED'];
const SESSION_STATUSES = ['ACTIVE', 'COMPLETED', 'FAULTED', 'CANCELLED'];
const CONNECTOR_TYPES  = ['CCS', 'CHAdeMO', 'Type2 AC', 'Type2 DC', 'Bharat AC', 'Bharat DC'];

module.exports = { ROLES, STATION_TYPES, ASSET_TYPES, CHARGER_STATUSES, SESSION_STATUSES, CONNECTOR_TYPES };
