#!/usr/bin/env bash
# One-shot local demo of the REAL loop: Alpha super admin creates a tenant,
# and that tenant gets a working login into the actual Livanto-based CRM
# (crm/) — not the unrelated backend/+frontend/ app scripts/dev-setup.sh
# demos. See crm/src/app/api/platform/provision-tenant/route.ts and
# platform/backend/src/services/tenants.service.js's create().
#
# Brings up 4 things:
#   Firebase emulators (Firestore :8080, Auth :9099) — crm/'s database,
#     run locally instead of a real Firebase project so this needs no
#     Firebase account/credentials to try.
#   platform/backend   :5100  (super admin API)
#   platform/frontend  :3100  (super admin UI)
#   crm/               :3200  (the real Livanto-based CRM)
#
# Usage:
#   ./scripts/dev-setup-crm.sh
#
# Override the Postgres role/password/host if your local setup needs it
# (e.g. Homebrew Postgres uses your OS username, not "postgres"):
#   PGUSER=$(whoami) PGPASSWORD= ./scripts/dev-setup-crm.sh
#
# Safe to re-run — every step is idempotent.
set -euo pipefail
cd "$(dirname "$0")/.."

PGUSER="${PGUSER:-postgres}"
PGPASSWORD_VAL="${PGPASSWORD-postgres}"
PGHOST="${PGHOST:-localhost}"
PGPORT="${PGPORT:-5432}"
PLATFORM_DB="${PLATFORM_DB:-alpha_platform}"

SUPER_ADMIN_EMAIL="${SUPER_ADMIN_EMAIL:-admin@alpha.com}"
SUPER_ADMIN_NAME="${SUPER_ADMIN_NAME:-Alpha Admin}"
SUPER_ADMIN_PASSWORD="${SUPER_ADMIN_PASSWORD:-Passw0rd!}"

TENANT_SLUG="${TENANT_SLUG:-xpulse}"
TENANT_NAME="${TENANT_NAME:-Xpulse}"
TENANT_CONTACT_NAME="${TENANT_CONTACT_NAME:-Xpulse Admin}"
TENANT_CONTACT_EMAIL="${TENANT_CONTACT_EMAIL:-admin@xpulse.example}"

PROVISION_SECRET="dev-provision-secret-not-for-production"

export PGPASSWORD="$PGPASSWORD_VAL"
PSQL="psql -h $PGHOST -p $PGPORT -U $PGUSER -v ON_ERROR_STOP=1"
DB_URL_BASE="postgresql://${PGUSER}:${PGPASSWORD_VAL}@${PGHOST}:${PGPORT}"

curl_json_field() {
  local expr="$1"; shift
  local body attempt
  for attempt in $(seq 1 15); do
    body=$(curl -s "$@") || body=""
    if [ -n "$body" ]; then
      if result=$(printf '%s' "$body" | node -pe "$expr" 2>/dev/null) && [ -n "$result" ] && [ "$result" != "undefined" ]; then
        printf '%s' "$result"
        return 0
      fi
    fi
    sleep 1
  done
  echo "Request never returned a usable response after 15 attempts: curl $*" >&2
  echo "Last response body: $body" >&2
  exit 1
}

free_port() {
  local port="$1" pids
  pids=$(lsof -ti tcp:"$port" 2>/dev/null || true)
  if [ -n "$pids" ]; then
    echo "    :$port already in use (pid $pids) — stopping it first."
    kill -9 $pids 2>/dev/null || true
    sleep 1
  fi
}

wait_for_port() {
  local port="$1" log="$2" i
  for i in $(seq 1 60); do
    # Prefer a raw TCP connect check (works in sandboxes where lsof can't
    # see other processes' sockets); fall back to lsof if /dev/tcp is
    # unavailable (e.g. non-bash /bin/sh).
    if (exec 3<>"/dev/tcp/127.0.0.1/$port") 2>/dev/null; then exec 3>&- 3<&-; return 0; fi
    if [ -n "$(lsof -ti tcp:"$port" 2>/dev/null || true)" ]; then return 0; fi
    sleep 0.5
  done
  echo "Nothing came up on :$port. Last 30 lines of $log:" >&2
  tail -30 "$log" >&2 || true
  exit 1
}

echo "==> Checking Postgres connectivity ($PGUSER@$PGHOST:$PGPORT)..."
if ! $PSQL -d postgres -tAc "select 1" >/dev/null; then
  echo "Could not connect to Postgres as '$PGUSER'. Set PGUSER/PGPASSWORD/PGHOST/PGPORT and retry." >&2
  echo "e.g. on Homebrew Postgres:  PGUSER=\$(whoami) PGPASSWORD= ./scripts/dev-setup-crm.sh" >&2
  exit 1
fi

echo "==> Creating the platform database (skips if it already exists)..."
$PSQL -d postgres -tAc "SELECT 1 FROM pg_database WHERE datname='$PLATFORM_DB'" | grep -q 1 || $PSQL -d postgres -c "CREATE DATABASE $PLATFORM_DB"

echo "==> Loading platform schema..."
$PSQL -d "$PLATFORM_DB" -f platform/database/schema.sql >/dev/null
for f in platform/database/migrations/*.sql; do $PSQL -d "$PLATFORM_DB" -f "$f" >/dev/null; done

write_env() {
  local file="$1"; shift
  printf '%s\n' "$@" > "$file"
  echo "    wrote $file"
}

echo "==> Writing .env files (always regenerated by this script)..."
write_env platform/backend/.env \
  "PORT=5100" \
  "DATABASE_URL=${DB_URL_BASE}/${PLATFORM_DB}" \
  "JWT_SECRET=dev-test-secret-for-sandbox-only" \
  "FRONTEND_URL=http://localhost:3100" \
  "NODE_ENV=development" \
  "PLATFORM_BASE_DOMAIN=alpha.app" \
  "CRM_PROVISION_URL=http://localhost:3200" \
  "CRM_PROVISION_SECRET=${PROVISION_SECRET}"

write_env platform/frontend/.env.local \
  "NEXT_PUBLIC_API_URL=http://localhost:5100/api" \
  "NEXT_PUBLIC_BASE_DOMAIN=alpha.app"

write_env crm/.env.local \
  "FIRESTORE_EMULATOR_HOST=localhost:8080" \
  "FIREBASE_AUTH_EMULATOR_HOST=localhost:9099" \
  "NEXT_PUBLIC_FIRESTORE_EMULATOR_HOST=localhost:8080" \
  "NEXT_PUBLIC_FIREBASE_AUTH_EMULATOR_HOST=localhost:9099" \
  "GCLOUD_PROJECT=demo-livanto" \
  "NEXT_PUBLIC_FIREBASE_PROJECT_ID=demo-livanto" \
  "NEXT_PUBLIC_FIREBASE_API_KEY=demo-api-key" \
  "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=demo-livanto.firebaseapp.com" \
  "PLATFORM_API_URL=http://localhost:5100/api" \
  "PLATFORM_PROVISION_SECRET=${PROVISION_SECRET}"

echo "==> Installing dependencies (skips a package if node_modules already exists)..."
for dir in platform/backend platform/frontend crm; do
  if [ -d "$dir/node_modules" ]; then
    echo "    $dir: node_modules present, skipping npm install"
  else
    echo "    $dir: npm install..."
    (cd "$dir" && npm install --no-audit --no-fund >/dev/null)
  fi
done

echo "==> Seeding super admin ($SUPER_ADMIN_EMAIL)..."
(cd platform/backend && npm run seed -- --email "$SUPER_ADMIN_EMAIL" --name "$SUPER_ADMIN_NAME" --password "$SUPER_ADMIN_PASSWORD" >/dev/null)

echo "==> Starting Firebase emulators (Firestore :8080, Auth :9099) — crm/'s database..."
free_port 8080
free_port 9099
if ! command -v firebase >/dev/null 2>&1; then
  echo "    firebase-tools not found globally, using npx (first run downloads it, can take a minute)..."
  FIREBASE_CMD="npx --yes firebase-tools"
else
  FIREBASE_CMD="firebase"
fi
[ -f crm/.firebaserc ] || printf '%s\n' '{"projects":{"default":"demo-livanto"}}' > crm/.firebaserc
(cd crm && nohup $FIREBASE_CMD emulators:start --project demo-livanto --only firestore,auth > /tmp/alpha-firebase-emulators.log 2>&1 &)
wait_for_port 8080 /tmp/alpha-firebase-emulators.log
wait_for_port 9099 /tmp/alpha-firebase-emulators.log

echo "==> Starting platform/backend on :5100..."
free_port 5100
(cd platform/backend && nohup npm run dev > /tmp/alpha-platform-backend.log 2>&1 &)
wait_for_port 5100 /tmp/alpha-platform-backend.log

echo "==> Starting platform/frontend on :3100..."
free_port 3100
(cd platform/frontend && nohup npm run dev > /tmp/alpha-platform-frontend.log 2>&1 &)
wait_for_port 3100 /tmp/alpha-platform-frontend.log

echo "==> Starting crm/ on :3200..."
free_port 3200
(cd crm && nohup npx next dev -p 3200 > /tmp/alpha-crm.log 2>&1 &)
wait_for_port 3200 /tmp/alpha-crm.log
# The Next.js dev server binds the port immediately but crm/'s first
# request still needs to finish compiling — the provisioning call below
# retries, but give it a head start so that isn't the first thing it does.
sleep 3

echo "==> Creating tenant '$TENANT_NAME' (slug: $TENANT_SLUG) via the super admin API — this also provisions its real CRM login..."
TOKEN=$(curl_json_field 'JSON.parse(require("fs").readFileSync(0,"utf8")).token' \
  -X POST http://localhost:5100/api/auth/login -H 'Content-Type: application/json' \
  -d "{\"email\":\"$SUPER_ADMIN_EMAIL\",\"password\":\"$SUPER_ADMIN_PASSWORD\"}")

EXISTING_TENANT=$(curl -s http://localhost:5100/api/tenants -H "Authorization: Bearer $TOKEN" \
  | node -pe "const d=JSON.parse(require('fs').readFileSync(0,'utf8')).data||[]; const t=d.find(x=>x.slug==='$TENANT_SLUG'); t?t.id:''" 2>/dev/null || true)

if [ -n "$EXISTING_TENANT" ]; then
  echo "    tenant already exists ($EXISTING_TENANT) — re-provisioning its CRM login (idempotent, safe to repeat)..."
  CRM_LOGIN_EMAIL="$TENANT_CONTACT_EMAIL"
  CRM_TEMP_PASSWORD=$(curl_json_field 'JSON.parse(require("fs").readFileSync(0,"utf8")).temporaryPassword' \
    -X POST http://localhost:3200/api/platform/provision-tenant -H 'Content-Type: application/json' -H "X-Provision-Secret: ${PROVISION_SECRET}" \
    -d "{\"slug\":\"$TENANT_SLUG\",\"name\":\"$TENANT_NAME\",\"adminEmail\":\"$TENANT_CONTACT_EMAIL\",\"adminName\":\"$TENANT_CONTACT_NAME\"}")
else
  RESPONSE=$(curl -s -X POST http://localhost:5100/api/tenants -H "Authorization: Bearer $TOKEN" -H 'Content-Type: application/json' \
    -d "{\"name\":\"$TENANT_NAME\",\"slug\":\"$TENANT_SLUG\",\"contact_name\":\"$TENANT_CONTACT_NAME\",\"contact_email\":\"$TENANT_CONTACT_EMAIL\",\"deployment_mode\":\"shared\"}")
  CRM_LOGIN_EMAIL=$(echo "$RESPONSE" | node -pe 'JSON.parse(require("fs").readFileSync(0,"utf8")).crmProvisioning.loginEmail')
  CRM_TEMP_PASSWORD=$(echo "$RESPONSE" | node -pe 'JSON.parse(require("fs").readFileSync(0,"utf8")).crmProvisioning.temporaryPassword')
  echo "    created tenant, CRM login provisioned."
fi

echo ""
echo "All set. Logs: /tmp/alpha-*.log, /tmp/alpha-firebase-emulators.log"
echo ""
echo "  Super admin:          http://localhost:3100/login"
echo "                         $SUPER_ADMIN_EMAIL / $SUPER_ADMIN_PASSWORD"
echo ""
echo "  $TENANT_NAME CRM login:      http://localhost:3200/login"
echo "                         $CRM_LOGIN_EMAIL / $CRM_TEMP_PASSWORD"
echo "                         (this is the real Livanto-based CRM — leads, sales,"
echo "                          operations, HRMS, settings — scoped to just this tenant)"
echo ""
echo "This runs crm/ against local Firebase emulators, not a real Firebase project —"
echo "data resets when you stop the emulators. Give crm/ a few seconds to finish"
echo "compiling its first page before opening it."
