/**
 * The EV Charging Station Franchise and Operation Agreement's fixed legal
 * text — preamble, recitals, the 27 numbered clauses, and the static
 * boilerplate of Schedules III and IV and the Annexure. Unlike the Letter of
 * Intent, this is never edited per lead (it's the same legal language for
 * every deal); only Schedule I (see AGREEMENT_SCHEDULE_FIELDS in
 * constants.ts, plus the Site Holder and Payment Model selections on
 * AgreementDoc), and Schedule II (chargingStationItems / infrastructureItems
 * on AgreementDoc) vary deal to deal. Sourced from the Livanto Standard
 * Franchise and Operation Agreement MASTER.
 *
 * Unlike the earlier Scenario A/B version of this template, the clause text
 * itself no longer forks per Site Holder — each affected clause is drafted
 * to read correctly on its own, qualified in-line ("where Livanto is the
 * Site Holder" / "where the Franchisee is the Site Holder") rather than
 * being duplicated as parallel Scenario-A and Scenario-B paragraphs.
 */

export interface AgreementClause {
  number: string;
  heading: string;
  paragraphs: string[];
}

export const AGREEMENT_TITLE = "EV CHARGING STATION FRANCHISE AND OPERATION AGREEMENT";

/** The opening "made and executed ... BY AND BETWEEN ..." block, before the Recitals. Franchisee particulars are filled from Schedule I, Part A at render time. */
export const AGREEMENT_PREAMBLE = [
  "This EV Charging Station Franchise and Operation Agreement (“Agreement”) is made and executed on the date and at the place of execution recorded below (“Effective Date”).",
  "BY AND BETWEEN LIVANTO GREEN INFRA PRIVATE LIMITED, a company incorporated under the Companies Act, 2013, bearing CIN: U35100UP2025PTC232160 and GSTIN: 09AAGCL4761J1Z4, having its registered office at G08-B, Loni Bhopura Road, Ghaziabad, Uttar Pradesh – 201005, and its office at 8th Floor, Infinity Techno Park, C56A/16, Block-C, Sector 62, Noida, Uttar Pradesh – 201309, acting through its authorised signatory duly empowered by a board resolution (hereinafter referred to as “Livanto” or the “Franchisor”, which expression shall, unless repugnant to the context or meaning thereof, include its successors and permitted assigns), of the FIRST PART;",
  "AND the Franchisee named in Schedule I, Part A, of the entity type, and having the PAN/CIN/LLPIN, GSTIN and registered/residential address recorded therein, acting through the authorised signatory named in Schedule I, Part A (hereinafter referred to as the “Franchisee”, which expression shall, unless repugnant to the context or meaning thereof, include its successors, permitted assigns, heirs, legal representatives and executors), of the SECOND PART.",
  "Livanto and the Franchisee are hereinafter referred to individually as a “Party” and collectively as the “Parties”.",
];

export const AGREEMENT_RECITALS = [
  "Livanto is engaged in the business of developing, owning, operating and managing electric vehicle charging infrastructure across India in the capacity of a Charge Point Operator (“CPO”), and offers third-party investors the opportunity to acquire and own EV charging equipment and associated infrastructure which Livanto thereafter installs, operates, maintains and commercialises on the owner's behalf under a Franchisee-Owned, Company-Operated (“FOCO”) model.",
  "The Charging Station the subject of this Agreement is to be established at the premises described in Schedule I, Part A (the “Site”). The Site is held by the Party identified in Schedule I as the Site Holder, under the lease, licence, title or other arrangement particularised in Schedule I (the “Site Agreement”). Where Livanto is the Site Holder, possession and control of the Site rests with Livanto and the Franchisee has no right, title or interest in the Site; where the Franchisee is the Site Holder, Clause 7.6 applies.",
  "The Franchisee is desirous of purchasing, and thereafter owning in its own name and on its own account, an EV charging station comprising the charging equipment described in Schedule I, Part B, together with the associated civil, electrical and site infrastructure, all as more particularly described in Schedule II (together the “Franchisee Assets”), and of having the same installed at the Site and operated, maintained and commercialised by Livanto on the terms set out herein.",
  "The Franchisee confirms that it has independently evaluated the commercial opportunity, the Site, the projected utilisation and the associated risks, and has obtained such independent legal, tax, technical and financial advice as it considers necessary, and that it is entering into this Agreement on the basis of its own commercial judgement and not in reliance upon any representation, projection or assurance not expressly recorded in this Agreement.",
  "The Parties now wish to record in writing the terms governing the sale of the Franchisee Assets to the Franchisee, the ownership of the Franchisee Assets by the Franchisee, the operation and management of the Charging Station by Livanto, and the commercial entitlements of each Party.",
];

/** The "NOW THEREFORE ..." operative words, immediately before Clause 1. */
export const AGREEMENT_OPERATIVE_WORDS =
  "NOW THEREFORE, in consideration of the mutual covenants, promises and obligations set out herein, and for other good and valuable consideration the receipt and sufficiency of which is acknowledged, the Parties agree as follows:";

export const AGREEMENT_CLAUSES: AgreementClause[] = [
  {
    number: "1", heading: "DEFINITIONS AND INTERPRETATION", paragraphs: [
      "1.1 Definitions. In this Agreement, unless the context otherwise requires, the following expressions shall bear the meanings assigned to them below.",
      "“Agreement” means this EV Charging Station Franchise and Operation Agreement together with all Schedules and the Annexure hereto, as amended in writing from time to time.",
      "“AMC” means the annual maintenance contract services in respect of the Charging Station, the scope, inclusions and exclusions of which are set out in Schedule III.",
      "“Applicable Law” means all statutes, rules, regulations, notifications, circulars, orders, directions, licences and permits of any governmental, statutory or regulatory authority in India, as in force from time to time.",
      "“Buyback Option” means the option of Livanto or its nominee to purchase the Franchisee Assets from the Franchisee in accordance with Clause 21.",
      "“Buyback Price” means the price computed in accordance with Clause 21.4 and Schedule I.",
      "“Charging Point” means each individual charging connector or gun forming part of the Charging Station and capable of delivering a charging session independently, as enumerated in Schedule I.",
      "“Charging Station” means the EV charging equipment purchased by and belonging to the Franchisee as described in Schedule II, Part A, and identified by make, model and serial number therein, together with such of its accessories, spares and factory-fitted components as are listed therein.",
      "“CMS” or “Charging Management System” means Livanto's proprietary OCPP-compliant central management system, mobile application, back-end software and payment infrastructure used for authorisation, metering, monitoring, billing and settlement of charging sessions.",
      "“COD” or “Commercial Commissioning Date” means the date on which the Charging Station is energised, integrated with the CMS and made available for public or commercial charging, as certified by Livanto in writing under Clause 6.4.",
      "“DISCOM” means the electricity distribution licensee having jurisdiction over the Site.",
      "“Electricity Cost” means the actual amount payable to the DISCOM in respect of electricity consumed at the Charging Station, including energy charges, fixed and demand charges, duties, cess and surcharges, computed on a per-kWh basis for the relevant Settlement Period.",
      "“Extension Period” means the further period specified in Schedule I following expiry of the initial term, as provided in Clause 4.3.",
      "“Fixed Monthly Amount” means the monthly sum specified in Schedule I, Part C, payable by Livanto to the Franchisee during the Fixed Payment Period under Clause 9.3, irrespective of Gross Revenue.",
      "“Fixed Payment Period” means, where Payment Model A is selected, the whole of the Term; and where Payment Model C is selected, the period specified in Schedule I, Part C, commencing on the COD.",
      "“Minimum Assured Amount” means the amount, if any, specified in Schedule I, Part C, payable during the Payout Period in accordance with Clause 9.5 by way of downside protection only, and not by way of assured or guaranteed return on the Franchisee's investment.",
      "“Payment Model” means Payment Model A (Fixed Payment), Payment Model B (Revenue Share) or Payment Model C (Fixed Payment followed by Revenue Share), whichever is recorded as applicable in Schedule I, Part C.",
      "“Payout Period” means the period, if any, specified in Schedule I, Part C, during which the Minimum Assured Amount is payable, commencing on the COD.",
      "“Force Majeure Event” has the meaning given in Clause 24.1.",
      "“Franchisee Assets” means the Charging Station and the Infrastructure Works together, each of which is funded by and belongs absolutely to the Franchisee.",
      "“Franchisee Earning” means the amount payable to the Franchisee during the Revenue Share Period, computed in accordance with Clause 9.4.",
      "“Gross Revenue” means the aggregate amount actually realised and credited to Livanto through the CMS from end-users in respect of charging sessions at the Charging Station during a Settlement Period, exclusive of GST and net of payment-gateway charges, refunds, chargebacks and failed-transaction reversals.",
      "“Infrastructure Works” means the civil works, foundations, canopy, cabling, trenching, feeder pillars, distribution boards, transformer, metering infrastructure, earthing, lighting, signage and all other site-side works and fixtures at the Site, other than the Charging Station, as described in Schedule II, Part B, all of which are funded by and belong to the Franchisee.",
      "“Land Usage Fee” means the per-kWh amount specified in Schedule I, Part C, applied during the Revenue Share Period on account of the Site, site rental and site upkeep, and retained by or paid to the Site Holder.",
      "“Livanto Fee” means the per-kWh amount specified in Schedule I, Part C, retained by Livanto during the Revenue Share Period towards operations, maintenance, software and management.",
      "“Public Selling Rate” means the per-kWh tariff charged to end-users at the Charging Station, determined in accordance with Clause 9.9.",
      "“Revenue Share Period” means, where Payment Model B is selected, the whole of the Term; and where Payment Model C is selected, the period commencing on expiry of the Fixed Payment Period, in each case continuing until expiry or termination of this Agreement and including the Extension Period.",
      "“Settlement Period” means each calendar month during the Term, the first such period commencing on the COD.",
      "“Site” has the meaning given in Recital B, and is more particularly described in Schedule I, Part A.",
      "“Site Holder” means the Party identified as such in Schedule I, Part A, being the Party which owns, leases or otherwise lawfully controls the Site.",
      "“Term” or “Tenure” means the period specified in Clause 4.1, together with the Extension Period where extended under Clause 4.3.",
      "“Units” means kilowatt-hours (kWh) of electricity dispensed through the Charging Station as recorded by the CMS in accordance with Clause 16.2.",
      "1.2 Interpretation.",
      "1.2.1 The headings and the index are for convenience only and shall not affect the construction of this Agreement.",
      "1.2.2 Words importing the singular include the plural and vice versa; words importing any gender include every gender.",
      "1.2.3 A reference to a statute is a reference to that statute as amended, re-enacted or replaced from time to time.",
      "1.2.4 “Including” and “in particular” are illustrative and shall not limit the generality of the preceding words.",
      "1.2.5 Where any period is expressed in days, it shall mean calendar days unless expressed as “business days”, in which case it means days on which scheduled commercial banks are open for business at the place of execution recorded above.",
      "1.2.6 The Schedules and the Annexure form an integral part of this Agreement. In the event of conflict between the body of this Agreement and Schedule I, Schedule I shall prevail in respect of commercial particulars only; in all other respects the body of this Agreement shall prevail.",
      "1.2.7 This Agreement has been jointly negotiated and reviewed by the Parties, each having had the opportunity to obtain independent legal advice, and no rule of construction requiring interpretation against the drafting Party shall apply.",
    ],
  },
  {
    number: "2", heading: "NATURE OF THE ARRANGEMENT AND LEGAL CHARACTERISATION", paragraphs: [
      "2.1 This Agreement records (a) a sale of goods and works by Livanto to the Franchisee; and (b) an independent contract for services under which Livanto operates, maintains and commercialises those assets on the Franchisee's behalf. Each element is separate and severable from the other.",
      "2.2 Nothing in this Agreement shall be construed as creating a partnership within the meaning of the Indian Partnership Act, 1932, an association of persons, a joint venture, an employment relationship, or a relationship of principal and agent between the Parties, save to the limited extent expressly stated in Clauses 5.2, 5.8 and 9. Neither Party shall hold itself out as having authority to bind the other. The amounts payable under Clause 9 are consideration for the respective contributions of each Party and shall not be construed as the sharing of the profits of a business carried on in common.",
      "2.3 This Agreement does not create, and shall not be construed as creating, any lease, sub-lease, tenancy, licence, easement, sub-letting or any right, title, interest or possession of any nature whatsoever in favour of the Franchisee in or over the Site or any part thereof. The Franchisee expressly acknowledges that it has no tenancy, occupancy or possessory rights over the Site, that possession and control of the Site rests with Livanto under the Site Agreement, and that it shall not assert any claim to the contrary at any time. This Clause 2.3 applies only where Livanto is the Site Holder. Accordingly, this Agreement is not compulsorily registrable under the Registration Act, 1908.",
      "2.4 The Franchisee acknowledges and confirms that: (a) its contribution is applied exclusively towards the purchase of specific, identified and separately titled assets belonging to the Franchisee and is not pooled with the contributions of any other person; (b) the Franchisee bears the commercial and market risk of those assets, including the risk of low utilisation, technological obsolescence and residual value; (c) no return of the Franchisee's capital is promised or assured by Livanto, and any Fixed Monthly Amount or Minimum Assured Amount is consideration for, or downside protection in respect of, the use and commercialisation of the Franchisee Assets, and is not a return of or on capital; and (d) accordingly, this Agreement does not constitute a collective investment scheme, a deposit, or any other regulated fund-raising arrangement. Livanto shall not accept any contribution from the Franchisee otherwise than against an invoice for the identified goods and works described in Schedule II.",
      "2.5 This Agreement grants the Franchisee no right to use the name, trade mark, service mark, trade dress, domain name, software or system of Livanto, save to the strictly limited extent set out in Clause 15.",
    ],
  },
  {
    number: "3", heading: "GRANT OF FRANCHISE RIGHTS", paragraphs: [
      "3.1 Subject to the terms of this Agreement and to receipt in full of the amounts payable under Schedule II, Livanto hereby grants to the Franchisee a non-exclusive, non-transferable, Site-specific right, for the duration of the Term, to have the Franchisee Assets installed at the Site and the Charging Station operated by Livanto as part of the Livanto charging network, and to receive the commercial entitlements set out in Clause 9.",
      "3.2 The rights granted hereunder are strictly limited to the Site. The Franchisee shall not sub-licence, assign, encumber (save as permitted under Clause 23.3) or otherwise transfer any right conferred under this Agreement without Livanto's prior written consent, such consent not to be unreasonably withheld.",
      "3.3 This Agreement confers no territorial exclusivity and no right of first refusal in respect of any other charging station opportunity of Livanto, except as expressly provided in Clause 3.4.",
      "3.4 Before offering any additional charging station opportunity at the Site to a third party, Livanto shall first offer it to the Franchisee by written notice specifying the commercial terms; the Franchisee shall have fifteen (15) days from receipt to accept in writing, failing which Livanto may offer it to any third party on terms no more favourable than those offered to the Franchisee.",
      "3.5 During the Term and for a period of one (1) year thereafter, the Franchisee shall not, at the Site, directly or indirectly establish, operate or permit the operation of any competing EV charging facility, or use any information obtained under this Agreement to do so.",
    ],
  },
  {
    number: "4", heading: "TERM, COMMENCEMENT, EXTENSION AND CONTINUITY OF LOCATION", paragraphs: [
      "4.1 Term. This Agreement shall come into force on the Effective Date. The initial term shall be the period specified in Schedule I, Part B, commencing on the COD, unless extended under Clause 4.3 or terminated earlier in accordance with Clause 20. All commercial entitlements, fees, financial protections and time-limited provisions shall be computed from the COD and not from the Effective Date.",
      "4.2 Commercial phasing. The commercial basis on which the Franchisee is paid throughout the Term is governed by the Payment Model selected in Schedule I, Part C. Where Payment Model C is selected, the initial term comprises (a) the Fixed Payment Period specified in Schedule I, Part C, running from the COD, during which Clause 9.3 applies; and (b) the balance of the initial term, during which Clause 9.4 applies.",
      "4.3 Extension Period. On expiry of the initial term, this Agreement shall stand extended for the further period specified in Schedule I, Part B (the “Extension Period”), unless the Franchisee gives Livanto not less than ninety (90) days' written notice before such expiry that it does not wish to extend. The Payment Model applicable at expiry of the initial term shall continue to apply throughout the Extension Period on the same basis, save as the Parties may otherwise agree in writing; and where Payment Model C is selected, Clause 9.4 shall apply throughout the Extension Period.",
      "4.4 Location during the Extension Period. The Extension Period shall be performed at the Site where Livanto's Site Agreement, or a successor arrangement in respect of the Site, then subsists. Where it does not, Livanto shall provide a commercially comparable alternative site and shall, at its own cost and at no additional cost whatsoever to the Franchisee, carry out the dismantling, transportation, re-installation, re-commissioning and all fresh Infrastructure Works required at that alternative site, and shall bear all DISCOM and statutory charges arising there. The Franchisee shall not be required to make any further payment on account of such relocation, and the Franchisee Assets shall continue to belong to the Franchisee at the alternative site.",
      "4.5 Further renewal. Not later than one hundred and eighty (180) days before expiry of the Extension Period, Livanto shall notify the Franchisee in writing whether it intends to continue operations. Where Livanto so intends, the Franchisee shall have a right of first refusal to renew this Agreement on the commercial terms then prevailing at Livanto's comparable sites, exercisable by written notice within thirty (30) days. If the Franchisee does not so exercise, Livanto shall be free to deal with the Site as it thinks fit and Clause 21 shall apply to the Franchisee Assets.",
    ],
  },
  {
    number: "5", heading: "SALE, OWNERSHIP AND TITLE TO THE FRANCHISEE ASSETS", paragraphs: [
      "5.1 Sale and consideration. Livanto shall sell and the Franchisee shall purchase the Franchisee Assets described in Schedule II for the consideration set out therein, payable in the instalments and on the milestones specified in Schedule II, Part C, plus GST and all other applicable taxes and duties. Livanto shall raise a tax invoice in the name of the Franchisee, and the Franchisee shall be entitled to claim input tax credit and depreciation in respect thereof in accordance with Applicable Law.",
      "5.2 Procurement as agent. Where any component of the Charging Station is procured by Livanto from a third-party original equipment manufacturer, Livanto shall do so for and on behalf of the Franchisee and shall procure that all manufacturer warranties are issued in favour of, or are assigned or otherwise made enforceable by, the Franchisee. Livanto shall deliver to the Franchisee copies of the OEM invoices, test certificates and warranty documents within thirty (30) days of the COD.",
      "5.3 Passing of title. Title in the Charging Station shall pass absolutely to the Franchisee upon the later of (a) receipt by Livanto of the full consideration therefor; and (b) delivery of the Charging Station to the Site. Title in the Infrastructure Works shall pass to the Franchisee progressively as they are executed and paid for, and in any event on the COD. Risk shall pass to the Franchisee on the COD, subject always to Clause 12. The Parties shall execute the Delivery, Installation and Title Certificate in the form set out in the Annexure within fifteen (15) days of the COD.",
      "5.4 Absolute ownership; no adverse claim. From the passing of title, the Franchisee shall be the sole and absolute legal and beneficial owner of the Franchisee Assets at all times during and after the Term. Livanto shall have no right, title, lien, charge or interest of any nature in or over the Franchisee Assets, save the right of possession as bailee under Clause 12 and the contractual rights under Clause 21. Livanto shall not sell, pledge, hypothecate, charge, encumber or part with possession of the Franchisee Assets, nor represent to any person that it owns the same.",
      "5.5 No accession; Franchisee Assets not to vest in Livanto. The Charging Station is and shall at all times remain movable property capable of severance and removal without material injury to the Site. Notwithstanding any degree of annexation to the Site, neither the Charging Station nor the Infrastructure Works shall become the property of Livanto or of the owner, lessor or association controlling the Site, and no right, title or interest therein shall vest in Livanto or in any mortgagee, chargeholder, successor-in-title or assignee of Livanto. In respect of any part of the Infrastructure Works which is affixed to the Site and cannot be severed without material injury to it, the Franchisee shall remain the beneficial owner thereof for the duration of the Term and the disposal of such part on expiry or termination shall be governed by Clause 21.9.",
      "5.6 Site consents and protection of the Franchisee Assets. Where Livanto is the Site Holder, Livanto warrants that the Site Agreement and all consents obtained by it from the owner, lessor or association controlling the Site permit (a) the execution of the Infrastructure Works at the Site; (b) the ownership of the Franchisee Assets by the Franchisee; and (c) the operation and, on expiry or termination, the removal of the Franchisee Assets. Livanto shall indemnify and keep indemnified the Franchisee against any claim, lien, distraint, demand or proceeding asserted over the Franchisee Assets by the owner, lessor or association controlling the Site, or any mortgagee, chargeholder, successor-in-title or assignee of either, and against any loss suffered by the Franchisee by reason of the Franchisee Assets being treated as belonging to the Site or to Livanto. Where the Franchisee is the Site Holder, the Franchisee gives the equivalent warranty in respect of its own title to or right of occupation of the Site and shall indemnify Livanto accordingly. Breach of this Clause 5.6 shall constitute a material breach entitling the other Party to terminate this Agreement under Clause 20.3 or 20.4 as applicable, without payment of any exit charge.",
      "5.7 Asset identification and insolvency protection. Livanto shall (a) affix and maintain on each unit of the Charging Station a durable plate stating “Owned by [Franchisee name]; operated by Livanto Green Infra Private Limited”; (b) record the Franchisee Assets in a register of third-party owned assets held on bailment or in trust, identifying the Franchisee as owner; and (c) not reflect the Franchisee Assets as assets of Livanto in its books of account or financial statements. The Franchisee Assets shall not form part of the assets of Livanto available to its creditors, and in the event of any insolvency, liquidation, resolution or winding-up proceeding in respect of Livanto, the Franchisee shall be entitled to identify, claim and repossess the Franchisee Assets as its own property.",
      "5.8 Infrastructure Works. The Infrastructure Works shall be executed and project-managed by Livanto, but the entire cost thereof shall be borne and funded by the Franchisee as part of the consideration set out in Schedule II, and the Infrastructure Works shall belong absolutely to the Franchisee. Livanto shall procure the Infrastructure Works for and on behalf of the Franchisee, shall raise its invoice therefor in the name of the Franchisee, and shall pass through to the Franchisee the benefit of all contractor and supplier warranties in respect thereof. Livanto shall have no right, title, lien, charge or interest in or over the Infrastructure Works. Save as expressly provided in Clauses 4.4 and 22.2, Livanto shall bear no part of the cost of the Charging Station or of the Infrastructure Works.",
      "5.9 Refund on non-delivery. If the Franchisee Assets are not installed and the COD not achieved by the Long-Stop Date specified in Schedule I for reasons solely attributable to Livanto (and not by reason of any matter contemplated by Clause 6.3), the Franchisee may by written notice require repayment of all amounts paid by it under this Agreement, and Livanto shall repay the same in full within thirty (30) days of such notice, together with simple interest at the rate specified in Schedule I from the date of receipt of each amount until repayment.",
    ],
  },
  {
    number: "6", heading: "INSTALLATION, COMMISSIONING AND TIMELINES", paragraphs: [
      "6.1 Livanto shall, as part of the consideration under Schedule II, undertake and complete the turnkey development of the Charging Station at the Site, including the Infrastructure Works, installation, electrical works, testing, DISCOM liaison, statutory approvals, commissioning and CMS integration, in accordance with Applicable Law and applicable Indian and international standards.",
      "6.2 Livanto shall use best endeavours to achieve the COD by the Scheduled COD specified in Schedule I and in any event by the Long-Stop Date specified therein.",
      "6.3 Stop-clock. The periods in Clause 6.2 shall be suspended, day for day, for any period during which (a) the Franchisee has failed to make a payment when due or to furnish any document, information, KYC, no-objection or approval required of it; (b) the DISCOM or any governmental, statutory or local authority, or the owner, lessor or association controlling the Site, has not issued a required approval, sanction, demand note, connection, clearance or no-objection, notwithstanding Livanto's diligent pursuit thereof; or (c) a Force Majeure Event subsists. The clock shall resume from the date each such impediment ceases. Delay attributable to any such cause shall not constitute a breach by Livanto, nor give rise to any claim for fee waiver, compensation, refund or damages.",
      "6.4 Livanto shall notify the Franchisee in writing of the COD within seven (7) days of its occurrence, enclosing the commissioning report, energisation confirmation and CMS activation record.",
      "6.5 The Site is subject to feasibility and regulatory approval. Livanto may relocate the exact position of the Charging Station or any Charging Point within the Site if the originally identified spot becomes unviable, at Livanto's cost; this shall not constitute a breach. If no viable alternative position within the Site can be identified within thirty (30) days, Clause 7.3 shall apply and, failing relocation, the Franchisee may terminate under Clause 20.4 with the refund consequence in Clause 5.9.",
    ],
  },
  {
    number: "7", heading: "THE SITE, SITE AVAILABILITY AND RELOCATION", paragraphs: [
      "7.1 Livanto's site obligations. Livanto shall maintain the Site Agreement in good standing throughout the Term, shall pay all charges due thereunder, and shall not surrender, terminate, materially vary or permit the forfeiture of the same in a manner that would prejudice the operation of the Charging Station. Livanto shall notify the Franchisee in writing within seven (7) days of receiving any notice of default, termination or non-renewal in respect of the Site. Livanto shall be responsible for site security, access control, upkeep, housekeeping, lighting and general availability of the Site, and for all dealings with the owner, lessor or association controlling the Site. This Clause 7.1 applies only where Livanto is the Site Holder.",
      "7.2 Site-level staffing. Where site-level personnel such as security, attendants or housekeeping are required, they shall be engaged, managed and paid for by the Site Holder, and all employment, statutory contribution and labour-law compliance in respect of such personnel shall be that Party's sole responsibility. Such costs are not part of any fee under Clause 9.",
      "7.3 Relocation. If the Site becomes permanently unviable at any time, including where the Site Agreement is terminated, forfeited or cannot be renewed on terms compatible with continued operation, Livanto shall, within thirty (30) days, offer the Franchisee a commercially comparable alternative site, and shall bear the entire cost of dismantling, transportation, re-installation, re-commissioning and fresh Infrastructure Works at such alternative site, at no additional cost whatsoever to the Franchisee. A completed relocation to a commercially comparable site in accordance with this Clause shall constitute due performance of Livanto's site-continuity obligation and shall not be a breach. The Franchisee Assets shall continue to belong to the Franchisee at the alternative site, and this Agreement shall continue in respect of that site as if it were the Site.",
      "7.4 Gap period. During any period in which the Charging Station is non-operational solely by reason of an active relocation, the Livanto Fee and Land Usage Fee shall not accrue and the Franchisee shall have no claim in respect of lost revenue, provided that any Fixed Monthly Amount shall continue to be payable during the Fixed Payment Period, and any unexpired portion of the Fixed Payment Period or Payout Period shall be extended by the duration of the relocation.",
      "7.5 Failure to relocate. If Livanto confirms in writing that no viable replacement site can be identified, or fails to provide written status updates at intervals of not more than thirty (30) days, or fails to complete relocation within one hundred and eighty (180) days of the Site becoming unviable, the Franchisee may terminate this Agreement by written notice, whereupon Livanto shall at its own cost dismantle and deliver the Charging Station to the Franchisee at a location nominated by the Franchisee, or, at the Franchisee's election, purchase the Franchisee Assets at the Buyback Price under Clause 21.",
      "7.6 Where the Franchisee is the Site Holder. Where Schedule I records the Franchisee as the Site Holder, the following shall apply in place of Clauses 7.1 and 7.3: (a) the Franchisee grants Livanto, for the duration of the Term, an irrevocable, non-exclusive right of access to and use of that part of the Site on which the Charging Station is installed, together with reasonable ancillary access for personnel, contractors, customers, DISCOM inspectors and emergency responders, such right being a bare licence which creates no interest in immovable property in favour of Livanto and determines automatically on expiry or termination; (b) the Franchisee shall maintain its title to or right of occupation of the Site in good standing throughout the Term, free from any encumbrance, attachment or third-party claim that would prejudice operation of the Charging Station, and shall be responsible for site security, upkeep and general availability of the Site; (c) Livanto shall be under no obligation to relocate where the Site becomes unavailable by reason of any matter affecting the Franchisee's own title or right of occupation, and any relocation then agreed shall be at the Franchisee's cost; and (d) the Franchisee shall not sell, lease or otherwise transfer the Site during the Term except subject to this Agreement and on the transferee executing a deed of adherence in favour of Livanto.",
    ],
  },
  {
    number: "8", heading: "ELECTRICITY CONNECTION, DISCOM AND STATUTORY APPROVALS", paragraphs: [
      "8.1 The dedicated electricity connection serving the Charging Station shall be applied for, obtained and maintained by Livanto in Livanto's own name. Livanto shall manage the entire DISCOM application, load sanction, energisation, metering and ongoing compliance process, and shall obtain all no-objection certificates required from the owner, lessor or association controlling the Site. Where the Franchisee is the Site Holder, the Franchisee shall promptly furnish all property documents, ownership proof and no-objection certificates required by the DISCOM.",
      "8.2 DISCOM charges and security deposit. The DISCOM security deposit, demand note charges, service line and development charges, transformer and power-infrastructure charges and all other one-time charges levied by the DISCOM shall be borne and funded by the Franchisee, and are included within the consideration set out in Schedule II. The quantum of such charges is determined solely by the DISCOM and cannot be ascertained at the date of this Agreement; accordingly, where the amount actually levied exceeds the provision made in Schedule II, Livanto shall invoice the excess to the Franchisee with supporting DISCOM documentation and the Franchisee shall pay the same within fifteen (15) days, and where it is less, the difference shall be refunded to or adjusted in favour of the Franchisee. The security deposit shall be held in Livanto's name for the account of the Franchisee; on closure of the connection or termination of this Agreement, Livanto shall pursue its refund and shall remit the amount actually recovered to the Franchisee, net of any statutory deduction and of any sum then due from the Franchisee to Livanto.",
      "8.3 Livanto shall obtain and maintain all approvals, permits, licences, no-objection certificates and statutory compliances required for the installation and operation of the Charging Station, including electrical inspectorate approval, fire and local body clearances. The statutory fees and charges payable to any authority shall be borne by the Franchisee as part of Schedule II; Livanto shall bear the cost of its own effort in obtaining them and shall keep the Franchisee indemnified against any penalty arising from Livanto's failure to obtain or maintain the same.",
      "8.4 During any Revenue Share Period the Electricity Cost shall be a pass-through in the settlement waterfall under Clause 9.4 and shall be borne out of Gross Revenue at actuals, without mark-up. During any Fixed Payment Period the Electricity Cost shall be borne by Livanto out of the Gross Revenue retained by it. Livanto shall furnish copies of DISCOM invoices on request.",
    ],
  },
  {
    number: "9", heading: "COMMERCIAL TERMS AND SETTLEMENT", paragraphs: [
      "9.1 All charging sessions at the Charging Station shall be authorised, metered, invoiced and collected exclusively through the CMS. Livanto shall collect all Gross Revenue as collecting agent. The Franchisee shall not, and shall not permit any person to, collect any consideration from end-users at the Charging Station otherwise than through the CMS.",
      "9.2 Selected Payment Model. The Franchisee's entitlement is determined by the Payment Model recorded in Schedule I, Part C, being one of: Payment Model A — Fixed Payment, under which Clause 9.3 applies for the whole of the Term; Payment Model B — Revenue Share, under which Clause 9.4 applies for the whole of the Term; or Payment Model C — Fixed Payment followed by Revenue Share, under which Clause 9.3 applies during the Fixed Payment Period and Clause 9.4 applies thereafter. A clause expressed to apply during the Fixed Payment Period or the Revenue Share Period has effect only where that period arises under the Payment Model selected.",
      "9.3 Fixed Payment — Payment Models A and C. Livanto shall pay the Franchisee the Fixed Monthly Amount specified in Schedule I, Part C, for each Settlement Period comprising the Fixed Payment Period, irrespective of the Units dispensed or the Gross Revenue actually realised at the Charging Station. During this period Livanto shall retain the whole of the Gross Revenue and shall bear the Electricity Cost, and the Franchisee shall have no entitlement to any share of Gross Revenue in addition to the Fixed Monthly Amount. Where the COD falls on a day other than the first day of a calendar month, the Fixed Monthly Amount for the first and last Settlement Periods shall be apportioned on a pro rata daily basis. The aggregate amount payable under this Clause over the Fixed Payment Period is as recorded in Schedule I, Part C.",
      "9.4 Revenue Share — Payment Models B and C. Where Payment Model B is selected this Clause applies from the COD; where Payment Model C is selected it applies from expiry of the Fixed Payment Period, upon which the Fixed Monthly Amount shall cease. For each Settlement Period, Gross Revenue shall be applied in the following order: (a) first, the Electricity Cost, at DISCOM actuals as a pure pass-through without mark-up; (b) second, the Land Usage Fee at the per-kWh rate specified in Schedule I, retained by or paid to the Site Holder; (c) third, the Livanto Fee at the per-kWh rate specified in Schedule I dispensed, retained by Livanto; and (d) the entire balance remaining shall be the Franchisee Earning and shall be paid to the Franchisee. Where in any Settlement Period the Gross Revenue is insufficient to meet items (a) to (c) in full, the shortfall shall be carried forward and recovered from the Gross Revenue of subsequent Settlement Periods, and the Franchisee shall not be required to fund any such shortfall out of its own resources.",
      "9.5 Minimum Assured Amount — optional downside protection under Payment Model B. This Clause applies only where Schedule I, Part C specifies a Minimum Assured Amount and a Payout Period. Where, in any Settlement Period falling within the Payout Period, the Franchisee Earning computed under Clause 9.4 is less than the Minimum Assured Amount, Livanto shall pay the shortfall to the Franchisee so that the Franchisee receives not less than the Minimum Assured Amount for that Settlement Period. This obligation (a) applies only during the Payout Period and shall not extend beyond it; (b) is subject to the maximum aggregate cap, if any, specified in Schedule I; (c) is a loss-bridging mechanism and does not constitute an assured, guaranteed or minimum return on the Franchisee's investment; and (d) shall be suspended for any period during which a Force Majeure Event, a relocation under Clause 7.3, or a suspension attributable to the Franchisee's default subsists, the Payout Period being correspondingly extended. Where no Minimum Assured Amount is specified in Schedule I, the Franchisee's entitlement under Payment Model B is the Franchisee Earning alone and Livanto gives no assurance as to its quantum.",
      "9.6 Settlement mechanics. Livanto shall, on or before the fifth (5th) day of each month, deliver to the Franchisee a statement of account for the preceding Settlement Period setting out Units dispensed, Gross Revenue, Electricity Cost, Land Usage Fee, Livanto Fee, taxes, and the net amount payable. Payment shall be made by electronic transfer to the Franchisee's designated bank account on or before the Settlement Date specified in Schedule I, for the preceding Settlement Period. All payments are exclusive of GST, which shall be charged and accounted for in accordance with Applicable Law, and are subject to deduction of tax at source where required. The Franchisee shall raise a valid tax invoice in respect of each settlement.",
      "9.7 Suspension. The obligation to pay the Fixed Monthly Amount or the Minimum Assured Amount shall be suspended, and the Fixed Payment Period or Payout Period correspondingly extended, only for any period during which a Force Majeure Event subsists under Clause 24, or a suspension attributable to the Franchisee's own default under Clause 13.2 subsists. The Fixed Monthly Amount shall not be suspended by reason of low utilisation, adverse market conditions, tariff movement or relocation under Clause 7.3.",
      "9.8 Disputed statements. If the Franchisee disputes any statement of account, it shall notify Livanto in writing with particulars within fifteen (15) days of receipt, failing which the statement shall be deemed accepted, save in the case of manifest error or fraud. The undisputed portion shall be paid on the due date irrespective of the dispute.",
      "9.9 Tariff. The Public Selling Rate shall be determined by Livanto having regard to network-wide pricing, DISCOM tariff, competitive conditions and Applicable Law, provided that (a) Livanto shall give the Franchisee not less than fifteen (15) days' prior written notice of any revision; (b) during any Revenue Share Period no revision shall be made which, on the utilisation then prevailing, would reduce the Franchisee Earning, without the Franchisee's prior written consent; and (c) any discount, promotional pricing, voucher or platform-level tariff reduction offered by Livanto shall be borne by Livanto and shall not reduce the Franchisee Earning. Where a DISCOM tariff increase renders the prevailing Public Selling Rate uneconomic, the Parties shall in good faith agree a revised Public Selling Rate within thirty (30) days.",
      "9.10 Subsidies and incentives. The availability of any capital subsidy, viability gap funding, incentive or grant in respect of EV charging infrastructure varies from State to State and is subject to approval on a project-by-project basis. No assurance is given as to availability, quantum, approval or timing of any subsidy, and neither Party shall have any claim against the other if a subsidy is delayed, reduced, rejected or withdrawn. Where any such benefit is applied for in respect of the Charging Station, the Party in whose name the application is made shall notify the other before applying, and the net amount received shall be shared in the proportion specified in Schedule I.",
      "9.11 Late payment. Any amount not paid when due shall carry simple interest at the rate specified in Schedule I from the due date until payment, without prejudice to any other remedy.",
    ],
  },
  {
    number: "10", heading: "OBLIGATIONS OF LIVANTO", paragraphs: [
      "10.1 Livanto shall, throughout the Term, and as part of the consideration set out in Schedule II: execute the Infrastructure Works and install, test and commission the Charging Station at the Site; obtain and maintain the DISCOM connection, sanctioned load and transformer arrangement, and all statutory approvals, permits, licences and no-objection certificates required for lawful operation; operate and manage the Charging Station as CPO, including CMS and OCPP integration, back-end connectivity, user authentication, payment gateway operation, customer support and 24x7 remote monitoring; provide preventive and corrective maintenance, AMC and warranty administration in accordance with Clause 13 and Schedule III; maintain site security, upkeep, housekeeping, lighting, signage and general availability of the Site where Livanto is the Site Holder, and manage all dealings with the owner, lessor or association controlling the Site; effect and maintain the insurances required under Clause 12.3; collect Gross Revenue, maintain accurate records, and pay the Franchisee in accordance with Clause 9; provide the Franchisee with real-time CMS dashboard access and the periodic reports required under Clause 16; comply with Applicable Law in the performance of its obligations, and maintain the Site Agreement in good standing; and promptly notify the Franchisee of any incident, accident, theft, vandalism, fire, electrical fault or material damage affecting the Franchisee Assets.",
      "10.2 Livanto shall exercise the degree of care, skill and diligence reasonably expected of a competent charge point operator, and shall maintain the Charging Station in good working order, fair wear and tear excepted, in accordance with the service levels in Clause 14.",
      "10.3 Livanto shall not, without the Franchisee's prior written consent, relocate the Charging Station outside the Site (save under Clauses 4.4 and 7.3), substitute or cannibalise any of its major components, or use it otherwise than for its intended purpose.",
    ],
  },
  {
    number: "11", heading: "OBLIGATIONS OF THE FRANCHISEE", paragraphs: [
      "11.1 The Franchisee shall pay the consideration for the Franchisee Assets in accordance with Schedule II, punctually and in full, time being of the essence in respect of such payments.",
      "11.2 The Franchisee shall furnish such KYC, PAN, GST, bank, constitutional and source-of-funds documentation as Livanto may reasonably require for compliance with Applicable Law, and shall promptly notify Livanto of any change therein.",
      "11.3 The Franchisee shall not interfere with, alter, reconfigure, tamper with or attempt to access the Charging Station, the CMS, the metering infrastructure, or the technical or operational parameters of any equipment at the Site, nor engage any third-party technician or contractor in respect of any work falling within Livanto's scope under Schedule III.",
      "11.4 The Franchisee shall not enter the operational area of the Site otherwise than with prior intimation to Livanto and subject to Livanto's safety protocols and any rules applicable at the Site, and shall not do or permit anything that interferes with Livanto's operations, the Site Agreement, or public access to the Charging Station.",
      "11.5 The Franchisee shall maintain confidentiality in accordance with Clause 17, and shall not make any public statement, press release or social media communication concerning Livanto, the Site or this Agreement without Livanto's prior written consent.",
      "11.6 The Franchisee shall promptly execute such acknowledgements, invoices, tax documents, insurance claim forms and confirmations as are reasonably necessary to give effect to this Agreement.",
    ],
  },
  {
    number: "12", heading: "CUSTODY, INSURANCE AND RISK", paragraphs: [
      "12.1 Bailment. The Franchisee, as bailor, delivers the Franchisee Assets into the possession of Livanto, as bailee, for the purpose of their operation, maintenance and commercialisation under this Agreement. Livanto shall take of the Franchisee Assets the degree of care required of a bailee under Sections 151 and 152 of the Indian Contract Act, 1872, and shall be responsible for loss of or damage to the Franchisee Assets occasioned by its failure to take such care. In respect of any part of the Infrastructure Works not capable of delivery as a chattel, Livanto shall hold the same for the account and benefit of the Franchisee on the same standard of care.",
      "12.2 Custody. Livanto shall hold the Franchisee Assets solely as bailee and shall not acquire any proprietary interest therein. Livanto shall not remove the Charging Station from the Site except under Clauses 4.4, 7.3, 13 (for repair) or 21, and shall in each such case notify the Franchisee in advance.",
      "12.3 Insurance. Livanto shall, at its cost, procure and maintain throughout the Term, in the name of the Franchisee as owner and named insured with Livanto endorsed as additional insured and loss payee to the extent of its insurable interest, the following policies with an insurer of good standing: (a) marine cum transit insurance during logistics; (b) erection all-risk insurance during installation; and (c) from the COD, comprehensive fire and special perils, burglary and theft, and electrical and mechanical breakdown cover for the full reinstatement value of the Charging Station, together with standard fire and special perils cover for the full reinstatement value of the Infrastructure Works. Livanto shall additionally maintain commercial general liability and public liability insurance (including cover under the Public Liability Insurance Act, 1991 where applicable) in respect of its operations at the Site.",
      "12.4 Evidence and claims. Livanto shall deliver certified copies of all policies and renewal certificates to the Franchisee within thirty (30) days of the COD and thereafter within fifteen (15) days of each renewal. Livanto shall pursue all claims diligently at its own cost. All insurance proceeds in respect of loss of or damage to the Franchisee Assets shall be applied first towards their repair or reinstatement and, where there is a total loss and no reinstatement, shall be paid to the Franchisee.",
      "12.5 Uninsured loss. Where any loss of or damage to the Franchisee Assets is not covered by insurance, or exceeds policy limits, or the claim is repudiated, the loss shall lie (a) with Livanto, to the extent caused by Livanto's breach, negligence, wilful misconduct or failure to procure or maintain the insurance required by Clause 12.3; and (b) otherwise with the Franchisee as owner, subject to Clause 19.",
      "12.6 Total loss. If the Charging Station suffers a total or constructive total loss, Livanto shall promptly notify the Franchisee. The Franchisee may, within sixty (60) days, elect either (a) to apply the insurance proceeds towards replacement, in which case this Agreement shall continue with the replacement equipment substituted into Schedule II and the Term and any Fixed Payment Period or Payout Period each extended by the period of interruption; or (b) to terminate this Agreement, in which case Livanto shall account to the Franchisee for all insurance proceeds and all amounts due to the date of termination, and neither Party shall have any further liability save for accrued rights and surviving provisions.",
    ],
  },
  {
    number: "13", heading: "WARRANTY, AMC AND OPERATIONS & MAINTENANCE", paragraphs: [
      "13.1 The consideration under Schedule II is inclusive of the warranty, AMC and operations and maintenance services described in Schedule III and Schedule IV, for the periods specified in Schedule I. Livanto shall administer all OEM warranty claims on the Franchisee's behalf at no additional charge.",
      "13.2 Warranty and AMC are subject to the exclusions set out in Schedule III and Schedule IV. Items falling outside those scopes shall be quoted separately and shall be undertaken only with the Franchisee's prior written approval; where the Franchisee withholds approval to a repair reasonably necessary for safe or lawful operation, Livanto may suspend operation of the affected Charging Point without liability and, during any Fixed Payment Period or Payout Period, the Fixed Monthly Amount or Minimum Assured Amount shall be reduced pro rata by reference to the rated capacity of the suspended Charging Point for the period of such suspension.",
      "13.3 All maintenance and operations services within the scope of Schedule III shall be provided exclusively by Livanto or its authorised contractors. The Franchisee shall not engage any third party for such work; any work so engaged shall void the warranty in respect of the affected components.",
      "13.4 Livanto shall maintain and make available to the Franchisee a maintenance log recording preventive checks, faults, downtime, resolutions, firmware updates and component replacements.",
    ],
  },
  {
    number: "14", heading: "SERVICE LEVELS, UPTIME AND LIQUIDATED DAMAGES", paragraphs: [
      "14.1 Livanto shall endeavour to maintain the average monthly uptime specified in Schedule I per Charging Point, computed on a best-effort basis and excluding downtime attributable to grid or DISCOM outages, telecommunications failure, Force Majeure Events, vandalism, theft, third-party or vehicle damage, site-side constraints, statutory shutdown, or any act or omission of the Franchisee.",
      "14.2 Livanto shall respond to a reported malfunction or outage within twenty-four (24) to forty-eight (48) hours and shall use best endeavours to rectify it within seven (7) days.",
      "14.3 Liquidated damages. Where a malfunction or outage attributable to Livanto continues beyond the seven (7) day period in Clause 14.2, Livanto shall pay the Franchisee liquidated damages at the rate specified in Schedule I per affected Charging Point per week or part thereof for so long as the default continues, subject to an aggregate cap in any calendar month of (a) during any Fixed Payment Period, one hundred percent (100%) of the Fixed Monthly Amount; and (b) during any Revenue Share Period, one hundred percent (100%) of the Minimum Assured Amount where one is specified, and otherwise of the average monthly Franchisee Earning over the preceding three Settlement Periods. The Parties confirm that this sum represents a genuine pre-estimate of the loss likely to be suffered, agreed after due deliberation, and is not in the nature of a penalty.",
      "14.4 Exclusive remedy. Liquidated damages under Clause 14.3 shall be the Franchisee's sole and exclusive monetary remedy for downtime and uptime shortfall, and shall be paid with the next settlement. Unused entitlement in any month shall not carry forward. Nothing in this Clause limits the Franchisee's right to terminate under Clause 20.4 for persistent breach.",
      "14.5 Attribution of downtime shall be determined from CMS records, remote monitoring data and field service reports. The Franchisee may challenge an attribution in writing within fifteen (15) days of receipt of the monthly statement, failing which the attribution shall be deemed accepted.",
    ],
  },
  {
    number: "15", heading: "BRANDING, MARKETING AND INTELLECTUAL PROPERTY", paragraphs: [
      "15.1 All branding, signage, livery, colour scheme and visual identity at the Site and on the Charging Station shall be as determined, approved and controlled solely by Livanto. Save as provided in Clause 15.2, the Franchisee shall not display, install, affix or otherwise use its name, logo, trade mark or branding at the Site, including on canopies, charging bays, entry and exit points, directional signage or any other promotional space.",
      "15.2 Notwithstanding Clause 15.1, the Franchisee shall be entitled to display, on the body of the charging unit only and in a form, size and position approved by Livanto in writing (such approval not to be unreasonably withheld), a discreet plate or decal bearing the Franchisee's name and identifying the Franchisee as the owner of the equipment. Such display shall not obstruct any operational, safety or statutory marking.",
      "15.3 The Franchisee shall be recognised as the Primary Location Partner and Livanto shall, at no cost to the Franchisee, list and feature the Charging Station on its mobile application, website and social media channels as part of standard network marketing. Such marketing is at Livanto's discretion as to format, frequency and content; any additional marketing activity requires Livanto's prior written consent and shall be at the Franchisee's cost.",
      "15.4 All intellectual property in the CMS, the OCPP integration, Livanto's software, mobile application, brand, trade marks, know-how, operating protocols, data models and documentation is and shall remain the exclusive property of Livanto. Nothing in this Agreement transfers, assigns or licences any such intellectual property to the Franchisee, save a non-exclusive, non-transferable, revocable right to access the CMS dashboard in respect of the Charging Station during the Term for its own information.",
      "15.5 All intellectual property embodied in the Charging Station equipment as supplied by the OEM shall pass to the Franchisee with the goods to the extent it does so by operation of law. Firmware, embedded software and CMS licences remain subject to their respective licence terms.",
    ],
  },
  {
    number: "16", heading: "DATA, REPORTING AND AUDIT", paragraphs: [
      "16.1 Livanto shall provide the Franchisee with (a) continuous read-only access to a CMS dashboard showing real-time and historical session data for the Charging Station; and (b) a monthly operational and financial report setting out Units dispensed, session count, Gross Revenue, Electricity Cost, fees deducted, downtime and the net amount payable. These reports shall be furnished throughout the Term, whichever Payment Model applies.",
      "16.2 The CMS meter reading, reconciled against the DISCOM meter, shall be the meter of record for computation of all per-kWh entitlements. Where a discrepancy exceeding two percent (2%) is identified between the CMS and the DISCOM meter, Livanto shall arrange calibration by an accredited agency within thirty (30) days and adjust the affected settlements accordingly.",
      "16.3 The Franchisee may, on not less than fifteen (15) days' written notice and not more than once in any financial year, at its own cost, appoint a chartered accountant to inspect and audit Livanto's records relating solely to the Charging Station. Where such audit reveals an under-payment exceeding five percent (5%), Livanto shall bear the reasonable cost of the audit and shall pay the shortfall with interest under Clause 9.11 within thirty (30) days.",
      "16.4 Each Party shall comply with Applicable Law relating to the processing of personal data of end-users. End-user data collected through the CMS shall belong to Livanto, and shall be shared with the Franchisee only in aggregated and anonymised form.",
    ],
  },
  {
    number: "17", heading: "CONFIDENTIALITY", paragraphs: [
      "17.1 Each Party shall keep confidential all commercial, technical, financial and operational information disclosed by the other in connection with this Agreement, and shall not disclose it without the discloser's prior written consent, during the Term and for three (3) years thereafter.",
      "17.2 The obligation in Clause 17.1 does not apply to information which (a) is or becomes public otherwise than through breach; (b) was lawfully in the recipient's possession free of restriction before disclosure; (c) is independently developed without use of the confidential information; or (d) is required to be disclosed by Applicable Law, court order or a regulatory or tax authority, provided the recipient gives the discloser prompt notice where lawful to do so.",
      "17.3 Each Party may disclose confidential information to its professional advisers, financiers, insurers and prospective transferees under equivalent obligations of confidence.",
    ],
  },
  {
    number: "18", heading: "REPRESENTATIONS AND WARRANTIES", paragraphs: [
      "18.1 Each Party represents and warrants to the other that, as at the Effective Date and throughout the Term: it has full power, capacity and authority to enter into and perform this Agreement, and the person executing it is duly authorised; this Agreement constitutes its legal, valid and binding obligation, enforceable in accordance with its terms; its execution and performance does not breach any law, order or agreement binding on it; no insolvency, winding-up, bankruptcy or resolution proceeding is pending or threatened against it, and it is able to pay its debts as they fall due; and it shall comply with all Applicable Law, including anti-bribery, anti-money-laundering and taxation law, in the performance of this Agreement.",
      "18.2 Livanto further represents and warrants that it holds a valid and subsisting right to the Site under the Site Agreement sufficient to permit the installation, ownership, operation and removal of the Franchisee Assets, and that it has obtained all consents required from the association and the owner of the Site for that purpose.",
      "18.3 The Franchisee further represents and warrants that the funds applied by it towards the purchase of the Franchisee Assets are from lawful sources, are its own or lawfully borrowed funds, and are not the proceeds of any unlawful activity.",
      "18.4 Save as expressly set out in this Agreement, and to the fullest extent permitted by Applicable Law, all conditions, warranties and representations, whether express, implied or statutory, are excluded. In particular, no representation, projection, financial model, presentation or illustration of utilisation, revenue or return provided at any time is or shall be construed as a warranty, guarantee or assurance of financial outcome, and the Franchisee confirms that it has not relied on any such material.",
    ],
  },
  {
    number: "19", heading: "INDEMNITY AND LIMITATION OF LIABILITY", paragraphs: [
      "19.1 Livanto shall be solely responsible for the operation, maintenance and statutory compliance of the Charging Station and shall ensure that it complies at all times with applicable operational, electrical, technical, environmental and safety standards.",
      "19.2 Livanto shall be liable for, and shall indemnify and hold harmless the Franchisee and its directors, partners, proprietor, officers, employees and representatives against, all losses, damages, liabilities, claims, costs and expenses (including reasonable legal fees) arising out of (a) any technical malfunction, electrical fault, operational failure, accident, fire, damage, injury or death, or any third-party or regulatory claim, arising from the installation, presence or operation of the Charging Station at the Site; (b) Livanto's breach of this Agreement, negligence, wilful misconduct or breach of Applicable Law; or (c) any claim relating to the Site, the Site Agreement or Livanto's right of possession thereto — save to the extent such loss is caused by the Franchisee's own breach, negligence or wilful misconduct, or by the condition of or title to the Site where the Franchisee is the Site Holder, or by a latent defect in the equipment for which the OEM is responsible and against which Livanto has diligently pursued the OEM warranty on the Franchisee's behalf, or by a Force Majeure Event.",
      "19.3 The Franchisee shall indemnify and hold harmless Livanto and its directors, officers, employees and representatives against all losses, damages, liabilities, claims, costs and expenses arising out of (a) the Franchisee's breach of this Agreement, negligence or wilful misconduct; (b) any misrepresentation by the Franchisee, including as to the source of funds; or (c) any interference by the Franchisee with the Charging Station, the CMS, the Site or Livanto's operations; or (d) where the Franchisee is the Site Holder, any claim relating to the Site, its title, condition, occupation or use.",
      "19.4 The Franchisee shall not be liable to any third party or authority for any technical malfunction, electrical fault, operational failure, accident, damage, injury or legal claim arising from the installation, presence or operation of the Charging Station, and Livanto shall assume conduct of and defend any such claim at its own cost, subject to the carve-outs in Clause 19.2.",
      "19.5 Cap on liability. Save in respect of (a) liability for death or personal injury caused by negligence; (b) fraud, wilful misconduct or gross negligence; (c) breach of Clause 17 (Confidentiality); (d) Livanto's obligations under Clause 5 (title and ownership), Clause 9 (payment obligations) and Clause 12 (custody and insurance); and (e) the indemnity obligations under Clauses 19.2 and 19.3 in respect of third-party claims — the aggregate liability of each Party under this Agreement shall not exceed the higher of (i) the total consideration paid by the Franchisee under Schedule II; and (ii) the aggregate amounts payable by Livanto to the Franchisee under Clause 9 during the twelve (12) Settlement Periods preceding the event giving rise to the claim.",
      "19.6 Neither Party shall be liable to the other for any indirect, incidental, special, exemplary, punitive or consequential loss, or for loss of profit, revenue, goodwill, anticipated savings or business opportunity, whether arising in contract, tort, statute or otherwise, save where such loss is the subject of a third-party claim covered by an indemnity under this Clause 19.",
      "19.7 The indemnified Party shall give prompt written notice of any claim, shall not admit liability or settle without the indemnifying Party's consent, and shall provide reasonable cooperation in the defence of such claim.",
    ],
  },
  {
    number: "20", heading: "DEFAULT AND TERMINATION", paragraphs: [
      "20.1 Lock-in. Save as provided in Clauses 5.6, 5.9, 6.5, 7.5, 12.6, 20.3, 20.4 and 24.3, neither Party shall be entitled to terminate this Agreement prior to expiry of the Term.",
      "20.2 Events of default. Each of the following constitutes an event of default by the Party concerned: (a) failure to pay any amount due for two (2) consecutive Settlement Periods, or any amount overdue by more than sixty (60) days; (b) material breach of any obligation under this Agreement not remedied within the applicable cure period; (c) persistent failure to maintain the service levels in Clause 14 continuing for thirty (30) days after written notice; (d) the commencement of any insolvency, winding-up, bankruptcy or corporate insolvency resolution proceeding which is not dismissed within sixty (60) days; (e) any representation under Clause 18 proving to have been materially untrue when made; or (f) conviction of the Party or its proprietor, partner, director or principal officer for any offence involving moral turpitude or fraud.",
      "20.3 Termination by Livanto. Livanto may terminate this Agreement by written notice if the Franchisee commits an event of default and fails to remedy it within thirty (30) days of written notice specifying the default (or fifteen (15) days in the case of a payment default).",
      "20.4 Termination by the Franchisee. The Franchisee may terminate this Agreement by written notice if Livanto commits an event of default — including failure to pay any amount due to the Franchisee under Clause 9 for two (2) or more consecutive Settlement Periods — and fails to remedy it within thirty (30) days of written notice specifying the default; or in any of the circumstances set out in Clauses 5.6, 5.9, 6.5, 7.5 or 12.6.",
      "20.5 Mutual exit. The Parties may at any time mutually agree in writing to terminate this Agreement early, on such terms as they may then agree, including as to the disposal of the Franchisee Assets under Clause 21.",
      "20.6 Unforeseen circumstances. Where a Party is prevented by genuinely unforeseen circumstances (including serious illness, incapacity or death of the Franchisee or its proprietor, or a change in Applicable Law rendering performance unlawful) from continuing with this Agreement, the Parties shall meet within thirty (30) days of written request and negotiate in good faith an orderly exit, including exercise of the Buyback Option under Clause 21 or a transfer under Clause 23.",
      "20.7 Termination shall be without prejudice to any right or remedy accrued as at the date of termination. Clauses 5.4, 5.5, 5.7, 12, 15.4, 17, 19, 21, 26 and 27 shall survive termination or expiry.",
    ],
  },
  {
    number: "21", heading: "CONSEQUENCES OF TERMINATION: REMOVAL, BUYBACK AND TRANSFER", paragraphs: [
      "21.1 The Franchisee Assets belong to the Franchisee, and nothing in this Clause shall entitle Livanto to retain, dispose of or deal with them otherwise than in accordance with this Clause 21.",
      "21.2 Franchisee's election. On expiry or termination of this Agreement for any reason, the Franchisee shall, within thirty (30) days, notify Livanto in writing of its election to: (a) require Livanto to purchase the Franchisee Assets at the Buyback Price, where Livanto has agreed or is obliged to exercise the Buyback Option under Clause 21.3; (b) take delivery of the Charging Station; or (c) offer the Franchisee Assets for sale to a third party, subject to Clause 21.6. Failing such election within ninety (90) days, the Franchisee shall be deemed to have elected option (b).",
      "21.3 Buyback Option. Livanto shall have the option, exercisable by written notice within thirty (30) days of the Franchisee's notice under Clause 21.2, to purchase the Franchisee Assets at the Buyback Price. Livanto shall be obliged to exercise this option where this Agreement is terminated (i) by the Franchisee under Clause 20.4; or (ii) under Clause 7.5. The Buyback Option is otherwise at Livanto's discretion, and no obligation on Livanto to repurchase, and no guarantee of residual value, is created by this Agreement.",
      "21.4 Buyback Price. The Buyback Price shall be the Original Equipment Cost specified in Schedule I, less straight-line depreciation at the rate specified in Schedule I for each completed year from the COD to the date of the exit notice, subject always to the floor percentage specified in Schedule I, together with the amount payable for the Infrastructure Works under Clause 21.9 where applicable. The Buyback Price shall be paid within forty-five (45) days of the exercise notice, against delivery of possession and execution of a transfer of title, and net of any amount then due from the Franchisee to Livanto. Where the Buyback Price cannot be agreed, it shall be determined by an independent registered valuer jointly appointed by the Parties, whose determination shall be final and binding; failing joint appointment within fifteen (15) days, the valuer shall be nominated by the President for the time being of the Institution of Valuers, India.",
      "21.5 Removal and de-installation. Where the Franchisee elects to take delivery under Clause 21.2(b), Livanto shall, within sixty (60) days, de-install the Charging Station and deliver it to the Franchisee at the Site or at such location within the State in which the Site is situated as the Franchisee may nominate. De-installation and delivery shall be at Livanto's cost where termination arises from Livanto's default or under Clauses 5.6, 5.9, 7.5 or 12.6, and otherwise at the Franchisee's cost. Livanto shall make good any damage to the Site caused by removal. Livanto shall have no lien over the Franchisee Assets in respect of any sum claimed by it, and shall not withhold delivery on that account; any such claim shall be pursued under Clause 26.",
      "21.6 Right of first refusal on sale. Before selling or otherwise disposing of the Franchisee Assets to any third party, whether during the Term or on termination, the Franchisee shall first offer them to Livanto by written notice specifying the price and terms. Livanto shall have twenty-one (21) days to accept in writing. If Livanto does not accept, the Franchisee may sell to a third party at a price not lower and on terms not more favourable than those offered to Livanto.",
      "21.7 Continuity on transfer. Where the Franchisee transfers the Franchisee Assets to a third party during the Term with Livanto's written consent, and such transferee executes a deed of adherence assuming all of the Franchisee's obligations under this Agreement, the Franchisee shall be released from obligations accruing after the date of transfer and no exit charge shall be payable.",
      "21.8 On expiry or termination, Livanto shall render a final statement of account within thirty (30) days and shall settle all amounts due to the Franchisee, including any unpaid Fixed Monthly Amount, Minimum Assured Amount or Franchisee Earning accrued to the date of termination, and the Franchisee shall settle all amounts due to Livanto, within a further thirty (30) days.",
      "21.9 Infrastructure Works on expiry or termination. The Infrastructure Works belong to the Franchisee but are affixed to the Site, which Livanto holds under the Site Agreement where Livanto is the Site Holder. Where the Franchisee is the Site Holder, the Infrastructure Works are situated on the Franchisee's own Site and shall simply remain with the Franchisee, and Livanto shall have no claim in respect thereof. Where Livanto is the Site Holder, on expiry or termination for any reason, the Franchisee may, by notice given with its election under Clause 21.2, require that the Infrastructure Works be dealt with as follows: (a) where Livanto or its nominee continues to operate a charging station at the Site, Livanto shall purchase the Infrastructure Works from the Franchisee at their written-down value, computed as the cost recorded in Schedule II, Part B, less straight-line depreciation over the Term, subject to the floor percentage specified in Schedule I, payable within forty-five (45) days; (b) the Franchisee may remove such of the Infrastructure Works as are capable of severance without material injury to the Site, at its own cost, making good any damage caused; or (c) failing (a) and (b), the Infrastructure Works shall be abandoned in situ and the Franchisee shall have no further claim in respect thereof. Where this Agreement is terminated by the Franchisee under Clause 20.4, or under Clauses 5.6, 5.9, 7.5 or 12.6, option (a) shall be obligatory on Livanto.",
    ],
  },
  {
    number: "22", heading: "UPGRADATION OF THE CHARGING STATION AND INFRASTRUCTURE", paragraphs: [
      "22.1 Livanto may, at its own discretion or at the Franchisee's request, upgrade or augment the Charging Station or the Infrastructure Works, including by installing higher-capacity chargers, additional Charging Points or additional electrical or civil infrastructure.",
      "22.2 Where an upgradation is undertaken at Livanto's own discretion and without the Franchisee's written agreement to fund it, the entire capital and infrastructure cost shall be borne by Livanto and any asset so funded shall belong to Livanto and shall be recorded as such in an amended Schedule II. Ownership of any upgraded or additional asset shall in all cases follow the Party which funded it.",
      "22.3 No upgradation shall, of itself, alter the commercial terms recorded in Schedule I, including the Payment Model, the Fixed Monthly Amount, the Minimum Assured Amount and the per-kWh rates, except to the extent expressly agreed in writing at the time. Any upgradation shall be recorded by way of a written amendment to Schedule I and Schedule II signed by both Parties.",
    ],
  },
  {
    number: "23", heading: "ASSIGNMENT, TRANSFER AND FINANCING", paragraphs: [
      "23.1 Neither Party may assign or novate its rights or obligations under this Agreement without the other Party's prior written consent, such consent not to be unreasonably withheld or delayed.",
      "23.2 Livanto may assign this Agreement to an affiliate or to a successor entity pursuant to a merger, amalgamation or sale of substantially the whole of its charging business, provided that (a) it gives the Franchisee thirty (30) days' prior written notice; (b) the assignee is of equivalent or better financial standing; and (c) the assignee executes a written undertaking in favour of the Franchisee acknowledging the Franchisee's ownership of the Franchisee Assets and assuming all of Livanto's obligations under this Agreement, including its payment obligations under Clause 9. Any purported assignment not complying with this Clause shall be void.",
      "23.3 Financing. The Franchisee may create a hypothecation, charge or security interest over the Franchisee Assets in favour of a scheduled bank or regulated non-banking financial company for the purpose of financing their purchase, on written notice to Livanto. Livanto shall, at the Franchisee's cost, execute such no-objection certificates, acknowledgements of ownership, invoices, asset confirmations and lender undertakings as such financier may reasonably require, and shall permit the financier reasonable access to inspect the Franchisee Assets on prior intimation. Livanto shall not be required to assume any payment obligation to the financier.",
    ],
  },
  {
    number: "24", heading: "FORCE MAJEURE", paragraphs: [
      "24.1 A “Force Majeure Event” means any event beyond the reasonable control of the affected Party which it could not have prevented by the exercise of reasonable diligence, including act of God, flood, earthquake, fire, storm, epidemic or pandemic, war, terrorism, riot, civil commotion, strike or lockout (other than of the affected Party's own workforce), sabotage, expropriation, change in Applicable Law rendering performance unlawful, government restriction or direction, and prolonged failure of the electricity grid or DISCOM supply.",
      "24.2 The affected Party shall notify the other in writing within seven (7) days of becoming aware of a Force Majeure Event, with particulars and an estimate of its duration, and shall use reasonable endeavours to mitigate its effects and to resume performance. Neither Party shall be liable for failure or delay in performance to the extent caused by a Force Majeure Event, and Livanto's obligation to pay the Fixed Monthly Amount or the Minimum Assured Amount shall be suspended for so long as it subsists, the Fixed Payment Period or Payout Period being correspondingly extended.",
      "24.3 If a Force Majeure Event continues for more than one hundred and eighty (180) consecutive days, either Party may terminate this Agreement by written notice, notwithstanding Clause 20.1, whereupon Clause 21 shall apply.",
    ],
  },
  {
    number: "25", heading: "NOTICES", paragraphs: [
      "25.1 Any notice under this Agreement shall be in writing in the English language and shall be delivered by hand against acknowledgement, by registered post or reputed courier, or by electronic mail with delivery confirmation, to the address set out in Schedule I or such other address as a Party may notify.",
      "25.2 A notice shall be deemed received: if delivered by hand, on delivery; if sent by registered post or courier, on the third business day after despatch; and if sent by electronic mail, on the business day following transmission, provided no delivery failure notification is received.",
      "25.3 Each Party shall designate a point of contact for day-to-day operational coordination. The Parties shall endeavour to meet at least once in each calendar quarter to review the performance of the Charging Station and to discuss operational matters.",
    ],
  },
  {
    number: "26", heading: "GOVERNING LAW AND DISPUTE RESOLUTION", paragraphs: [
      "26.1 This Agreement and all matters arising out of or in connection with it, including its existence, validity, interpretation, performance, breach and termination, shall be governed by and construed in accordance with the laws of India.",
      "26.2 In the event of any dispute, difference or claim arising out of or in connection with this Agreement, the aggrieved Party shall serve a written notice of dispute on the other, and the Parties shall endeavour in good faith to resolve the same through discussion between their senior representatives within thirty (30) days of such notice.",
      "26.3 Failing amicable resolution within the said period, the dispute shall be finally resolved by arbitration under the Arbitration and Conciliation Act, 1996 (as amended), before a sole arbitrator appointed by mutual written consent of the Parties within thirty (30) days of the reference. Failing such agreement, the sole arbitrator shall be appointed on the application of either Party in accordance with Section 11 of the said Act. The seat and legal place of arbitration shall be as specified in Schedule I; the venue may be such other place as the arbitrator may determine for convenience without altering the seat. The language of the arbitration shall be English. The arbitral award shall be final and binding. Each Party shall bear its own costs and the Parties shall share the arbitrator's fees equally, subject to the arbitrator's power to award costs.",
      "26.4 Subject to Clause 26.3, the courts at the seat specified in Schedule I shall have exclusive jurisdiction, including for the purpose of applications under Sections 9, 11, 34 and 36 of the Arbitration and Conciliation Act, 1996.",
      "26.5 Nothing in this Clause shall prevent either Party from seeking urgent interim or injunctive relief from a court of competent jurisdiction, including for the protection or recovery of the Franchisee Assets.",
      "26.6 Notwithstanding any dispute, each Party shall continue to perform its obligations under this Agreement, and Livanto shall continue to make the payments due under Clause 9 and settle undisputed amounts due to the Franchisee.",
    ],
  },
  {
    number: "27", heading: "GENERAL", paragraphs: [
      "27.1 This Agreement, together with its Schedules and the Annexure, constitutes the entire agreement between the Parties in respect of its subject matter and supersedes all prior negotiations, understandings, memoranda of understanding, letters of intent, expressions of interest, proposals, presentations, financial models and any earlier form of franchise agreement circulated between the Parties in respect of the Site.",
      "27.2 No amendment or variation of this Agreement shall be effective unless made in writing and signed by the authorised representatives of both Parties.",
      "27.3 No failure or delay by a Party in exercising any right shall operate as a waiver, and no single or partial exercise shall preclude any further exercise. A waiver is effective only if in writing.",
      "27.4 If any provision of this Agreement is held to be invalid, illegal or unenforceable, that provision shall be severed and the remaining provisions shall continue in full force and effect, and the Parties shall negotiate in good faith a valid substitute provision achieving as nearly as possible the original commercial intent.",
      "27.5 This Agreement may be executed in counterparts, including by electronic signature, each of which shall constitute an original and all of which together shall constitute one instrument.",
      "27.6 The stamp duty payable on this Agreement shall be borne by the Franchisee and shall be paid at the rate applicable in the State of execution. Each Party shall bear its own legal and professional costs.",
      "27.7 This Agreement is executed in two (2) originals, one to be retained by each Party.",
    ],
  },
];

/** Schedule II, Part D — the fixed statement (no per-lead figures) that warranty/AMC/O&M is included in the consideration at no extra charge, subject to the exclusions in Schedules III and IV. */
export const AGREEMENT_SCHEDULE_II_PART_D_NOTE =
  "The consideration in Part C of this Schedule II is inclusive of: the OEM/Livanto equipment warranty for the period specified in Schedule I, Part C (terms per Schedule IV); AMC charger-level maintenance from expiry of warranty to the end of the period specified in Schedule I (scope per Schedule III); and O&M infrastructure maintenance from the COD to the end of the period specified in Schedule I (scope per Schedule III) — at no additional charge to the Franchisee for the scopes stated, subject to the exclusions in Schedules III and IV.";

/** Schedule III — Scope of Operations & Maintenance and AMC. Fixed boilerplate, no per-lead fields. */
export const AGREEMENT_SCHEDULE_III: AgreementClause[] = [
  {
    number: "A", heading: "Framework and Applicability", paragraphs: [
      "A.1 During the warranty period specified in Schedule I, the Charging Station remains covered under OEM / Livanto warranty. All monitoring, predictive diagnostics, firmware updates, remote support and preventive maintenance described in this Schedule shall nonetheless be provided from Day 1 as part of standard operational service; only the cost responsibility for replacement of major components follows the warranty terms.",
      "A.2 AMC becomes financially active on expiry of the warranty period and covers charger-level technical maintenance as set out in Part B.",
      "A.3 O&M applies from the COD in respect of all civil and electrical infrastructure installed at the Site, as set out in Part C.",
      "A.4 Livanto shall endeavour to resolve all AMC and O&M covered issues promptly. Most faults are resolved within twenty-four (24) to forty-eight (48) hours through remote diagnostics or on-site intervention. A maximum best-effort window of seventy-two (72) hours applies, to allow for factors beyond Livanto's reasonable control including DISCOM outages, adverse weather, OEM part unavailability and site-access limitations. Out-of-scope issues shall be communicated to the Franchisee as soon as practicable with an indicative cost and timeline.",
    ],
  },
  {
    number: "B", heading: "AMC Scope — Charger Maintenance", paragraphs: [
      "B.1 Inclusions: proactive preventive maintenance (periodic checks covering module health, internal terminations, cooling systems, protective devices (MCB, RCCB, SPD), wiring integrity, connectors, enclosure sealing and system performance); 24x7 remote monitoring (continuous monitoring of voltage and current patterns, imbalance, internal temperatures, OCPP connectivity and thermal or fault anomalies, with auto-triggered alerts); predictive diagnostics (trend analysis of tripping events, thermal deviations, module degradation, sensor drift and fault-frequency patterns); firmware and configuration management (firmware upgrades, security patches, parameter tuning, remote debugging and log extraction); reactive corrective maintenance (on-demand troubleshooting and repair of relays, fuses, auxiliary electronics, sensors, control wiring, cooling fans and internal communication wiring); warranty coordination (OEM claim filing, component logistics and diagnostic support during the warranty period); and maintenance reporting (documentation of preventive checks, fault resolutions, firmware updates and health summaries).",
      "B.2 Exclusions: AMC does not cover (a) major power components including rectifier modules, PLC/CPU, charger guns post-warranty, displays, AC/DC meters post-warranty and communication modules; and (b) failures caused by water ingress, flooding, vandalism, vehicle impact, rodent damage, civil leaks, electrical surges, unauthorised work, theft or Force Majeure Events. Excluded items shall be quoted and addressed separately, subject to the Franchisee's written approval. The exclusions in this Part B.2 apply irrespective of whether the failure or degradation of an excluded component could have been identified, predicted or prevented through the preventive or predictive maintenance activities in Part B.1.",
    ],
  },
  {
    number: "C", heading: "O&M Scope — Infrastructure Maintenance", paragraphs: [
      "C.1 Inclusions: remote electrical health monitoring (continuous monitoring of voltage, current, load imbalance, breaker health, power factor and thermal stress indicators, with automated alerts); predictive maintenance response (intervention on abnormal remote readings, tripping events or thermal signatures to prevent downtime before failure); quarterly on-site inspections (LT panels, DBs, junction boxes, switchgear, earthing pits, cable routing, conduit integrity, charger pedestals, bollards, foundations, charging bay condition, safety markings and sensor/communication module health); reactive on-demand support (mobilisation of technicians for O&M-scope issues with technical troubleshooting and rectification); preventive infrastructure upkeep (tightening of lugs, earthing integrity checks, thermal hotspot verification, panel health checks, relay testing and structural/wiring safety evaluation); and safety compliance readiness (ensuring the infrastructure remains compliant with applicable EV safety norms for safe public operation).",
      "C.2 Exclusions: O&M does not cover major civil reconstruction including trenching, cable re-laying and re-pedestalling; damage due to waterlogging, flooding, construction activity or actions of the owner, lessor, association, residents or third parties at the Site; transformer or RMU faults; vandalism, theft or vehicle impact; Force Majeure Events; damage from unauthorised site work; and any change to site layout outside the original project scope. Such work shall be quoted and carried out separately, subject to the Franchisee's written approval. Where Livanto is the Site Holder, the exclusion for site-owner-side actions applies only to events genuinely beyond Livanto's reasonable control despite its control of the Site under the Site Agreement, and does not exclude damage arising from Livanto's own failure to manage that relationship with reasonable care. Where the Franchisee is the Site Holder, all site-side and owner-side actions are excluded without qualification.",
    ],
  },
  {
    number: "D", heading: "Uptime, Attribution and Fee Adjustment", paragraphs: [
      "Uptime measurement, downtime attribution and the consequences of Livanto-attributable downtime are governed by Clause 14. Liquidated damages apply only to the affected Charging Point and shall not be aggregated across Charging Points or months. No adjustment applies where the Franchisee is in default of any payment obligation as at the date the downtime occurs.",
    ],
  },
];

/** Schedule IV — Warranty Terms. Fixed boilerplate, no per-lead fields. */
export const AGREEMENT_SCHEDULE_IV: AgreementClause = {
  number: "", heading: "WARRANTY TERMS", paragraphs: [
    "1. Livanto provides, and shall procure that the OEM provides, a limited warranty for the period specified in Schedule I, Part C, from the COD, in respect of the charger equipment supplied under this Agreement. The warranty period is linked to the COD and shall not be extended by any repair or component replacement carried out during that period, save that a replaced major component shall carry the balance of the original warranty or ninety (90) days, whichever is longer.",
    "2. The warranty covers manufacturing defects in materials and workmanship arising under normal and intended use. During the warranty period, defective components identified as manufacturing defects following inspection shall be repaired or replaced. Major charger components including power modules, controller systems, display units, charging gun assemblies and factory-fitted internal parts are covered, subject to the exclusions below.",
    "3. The warranty does not cover: normal wear and tear arising from ordinary use; damage caused by events beyond reasonable operational control including fire, flood, lightning, electrical surge, natural calamity or Force Majeure; loss, theft, vandalism, accidental external impact or third-party interference; damage arising from unauthorised repair, modification or use of non-approved spares; consumables; and cosmetic damage not affecting function.",
    "4. Warranty claims shall be administered by Livanto on the Franchisee's behalf at no additional cost. Livanto shall pursue OEM claims diligently and shall keep the Franchisee informed of their status. Where the OEM repudiates a claim, Livanto shall notify the Franchisee with the OEM's written reasons.",
    "5. Losses excluded from warranty may be recoverable under the insurances maintained under Clause 12.3, and Livanto shall pursue such insurance claims on the Franchisee's behalf.",
  ],
};

/** Annexure — Delivery, Installation and Title Certificate. Static preamble/certificate text; the equipment/serial-number table is populated per lead from chargingStationItems/infrastructureItems. */
export const AGREEMENT_ANNEXURE_A_HEADING = "DELIVERY, INSTALLATION AND TITLE CERTIFICATE";
export const AGREEMENT_ANNEXURE_A_SUBTITLE =
  "(To be executed by both Parties within fifteen (15) days of the Commercial Commissioning Date, pursuant to Clause 5.3)";
export const AGREEMENT_ANNEXURE_A_INTRO =
  "With reference to the EV Charging Station Franchise and Operation Agreement between Livanto Green Infra Private Limited and the Franchisee named in Schedule I, Part A, the Parties hereby record and confirm as follows:";
export const AGREEMENT_ANNEXURE_A_PARAGRAPHS = [
  "1. The Franchisee Assets described in Schedule II of the Agreement, comprising the charging equipment and the associated Infrastructure Works, have been delivered to and installed at the Site and have been commissioned.",
  "2. The Commercial Commissioning Date is as recorded below. The Fixed Payment Period and/or Payout Period specified in Schedule I, as applicable to the Selected Payment Model, commences on that date.",
  "3. The Franchisee has paid the full consideration under Schedule II, and Livanto acknowledges receipt thereof.",
  "4. Title in the Charging Station and in the Infrastructure Works has passed absolutely to the Franchisee, and the Franchisee is the sole and absolute owner of the Franchisee Assets. Livanto holds the Franchisee Assets solely as bailee under Clause 12 of the Agreement and asserts no right, title, lien or interest therein.",
  "5. The ownership identification plate required by Clause 5.7(a) has been affixed to each unit.",
  "6. Livanto has delivered to the Franchisee copies of the OEM invoices, test certificates, warranty documents and insurance policies required under the Agreement.",
];
